const SET_CATEGORY = 'SET_CATEGORY';
const SET_PROFESSION = 'SET_PROFESSION'
const SET_AGE_TO = 'SET_AGE_TO';
const SET_AGE_FROM = 'ADD_AGE_FROM';
const SET_QUALIFICATION = 'SET_QUALIFICATION'
const SET_CITY = 'SET_CITY';
const SET_SALARY_FROM = 'SET_SALARY_FROM';
const SET_SALARY_TO = 'SET_SALARY_TO';
const SET_CURRENCY = 'SET_CURRENCY'

export { SET_CURRENCY, SET_SALARY_FROM, SET_SALARY_TO, SET_PROFESSION, SET_CATEGORY, SET_AGE_TO, SET_AGE_FROM, SET_QUALIFICATION, SET_CITY };
