const SET_LIST = 'SET_LIST';
const SET_LOADING = 'SET_LOADING';
const WATCH_CV = 'WATCH_CV'
const SET_TYPE = 'SET_TYPE'
const SET_MY_CV_LIST = 'SET_MY_CV_LIST'
const SET_ID = 'SET_ID'

export {
  SET_MY_CV_LIST,
  SET_LIST,
  SET_LOADING,
  WATCH_CV,
  SET_TYPE,
  SET_ID
};
