const UPDATE_PHONE = 'UPDATE_PHONE'
const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'
const UPDATE_PROFESSION = 'UPDATE_PROFESSION'
const UPDATE_CITY = 'UPDATE_CITY'
const UPDATE_QUALIFICATION = 'UPDATE_QUALIFICATION'
const UPDATE_EXPERIENCE = 'UPDATE_EXPERIENCE'
const UPDATE_TOOLS = 'UPDATE_TOOLS'
const UPDATE_NAME = 'UPDATE_NAME'

export { UPDATE_NAME, UPDATE_TOOLS, UPDATE_PHONE, UPDATE_LANGUAGE, UPDATE_PROFESSION, UPDATE_CITY, UPDATE_QUALIFICATION, UPDATE_EXPERIENCE }