const SET_PROFILE = 'SET_USER_PROFILE';
const SET_LOADING = 'SET_USER_LOADING';
const SET_PROFILE_ADS = 'SET_USER_ADS';
const SET_NOTIFICATION_SETTINGS = 'SET_NOTIFICATION_SETTINGS';
const SET_PROFILE_ADS_STATUS = 'SET_USER_ADS_STATUS';
const SET_AVATAR = 'SET_AVATAR';
const SET_USER_TYPE = 'SET_USER_TYPE'

export {
  SET_USER_TYPE,
  SET_PROFILE,
  SET_LOADING,
  SET_PROFILE_ADS,
  SET_NOTIFICATION_SETTINGS,
  SET_PROFILE_ADS_STATUS,
  SET_AVATAR,
};
